name: MCPP_PACKAGE_AND_RELEASE

on:
  push:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: nelonoel/branch-name@v1.0.1
    
    - name: Rollback Release
      uses: author/action-rollback@stable
      continue-on-error: true
      with:
        tag: ${{ env.BRANCH_NAME }}-latest
        delete_orphan_tag: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.BRANCH_NAME }}-latest
        release_name: ${{ env.BRANCH_NAME }}
        draft: false
        prerelease: false
    
    - uses: actions/checkout@v2
    
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url}}  
  
  buidl-and-package:
    needs: [release]
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v2
    
    - name: build.py
      run: python .github/workflows/build.py
      working-directory: ${{ github.workspace }}
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: mcpp-${{ runner.os }}
        path: ${{ github.workspace }}/mcpp.zip
    
    - name: Release Addon
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.release.outputs.upload_url }}
        asset_path: ${{ github.workspace }}/mcpp.zip
        asset_name: mcpp-${{ runner.os }}.zip
        asset_content_type: application/zip

